### ISSUE TITLE
model_onnx not working in toolkit.

### ISSUE THREAD

**Issue by georgiosn** [mammoth-eu/mammoth-commons#20]
Latest model onnx does not work in the toolkit the error log in KFP is the following:

Input:
{"path": "http://host.k3d.internal:5000/model.onnx"}

```
time="2024-10-21T12:27:54.406Z" level=info msg="capturing logs" argo=true
time="2024-10-21T12:27:54.499Z" level=info msg="capturing logs" argo=true
I1021 12:27:54.552514      32 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "model_onnx__params": {
        "parameterType": "STRUCT",
        "defaultValue": {
          "path": ""
        },
        "isOptional": true
      }
    }
  },
  "outputDefinitions": {
    "artifacts": {
      "output": {
        "artifactType": {
          "schemaTitle": "system.Model",
          "schemaVersion": "0.0.1"
        }
      }
    },
    "parameters": {
      "Output": {
        "parameterType": "STRING"
      }
    }
  },
  "executorLabel": "exec-model-onnx"
}
I1021 12:27:54.555105      32 cache.go:116] Connecting to cache endpoint 10.43.199.76:8887
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[KFP Executor 2024-10-21 12:28:00,145 INFO]: --component_module_path is not specified. Looking for component `model_onnx` in config file `kfp_config.ini` instead
[KFP Executor 2024-10-21 12:28:00,147 INFO]: Loading KFP component "model_onnx" from catalogue/model_loaders/onnx.py (directory "catalogue/model_loaders" and module name "onnx")
[KFP Executor 2024-10-21 12:28:00,401 INFO]: Got executor_input:
{
    "inputs": {
        "parameterValues": {
            "model_onnx__params": {
                "path": "http://host.k3d.internal:5000/model.onnx"
            }
        }
    },
    "outputs": {
        "parameters": {
            "Output": {
                "outputFile": "/tmp/kfp/outputs/Output"
            }
        },
        "artifacts": {
            "output": {
                "artifacts": [
                    {
                        "type": {
                            "schemaTitle": "system.Model",
                            "schemaVersion": "0.0.1"
                        },
                        "uri": "minio://mlpipeline/v2/artifacts/tabular1/99380ae6-52c9-43db-b439-057396760948/model-onnx/output"
                    }
                ]
            }
        },
        "outputFile": "/tmp/kfp_outputs/output_metadata.json"
    }
}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 109, in <module>
    executor_main()
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main
    output_file = executor.execute()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor.py", line 361, in execute
    result = self.func(**func_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 20, in kfp_method
NameError: name 'pickle' is not defined
I1021 12:28:00.660152      32 launcher_v2.go:151] publish success.
F1021 12:28:00.660295      32 main.go:49] failed to execute component: exit status 1
time="2024-10-21T12:28:01.507Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-10-21T12:28:02.411Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

**Comment by maniospas** [comment]
If you already have the files locally, can you try to add `import pickle` at the first lines of `mammoth/integration.py` ?
Please tell me if you cannot or if this fixes this issues.

This would be the same fix for most `NameError: name 'XXX' is not defined,` but do open issues for each of them to make sure that they are all addressed.

**Comment by georgiosn** [comment]
Thanks for the suggestion!

Now for the above input I get the following error.

Has issues with http:// links?

```
Version: [2.2.0](https://www.github.com/kubeflow/pipelines/commit/dd59f48cdd0f6cd7fac40306277ef5f3dad6e263)
[Report an Issue](https://github.com/kubeflow/pipelines/issues/new/choose)
[Experiments](http://kfp.local.exus.ai:8082/#/experiments)
[Tabular](http://kfp.local.exus.ai:8082/#/experiments/details/54dad6ff-1e0f-44e3-9a07-aff05d2e79f5)
Tabular2
Layers
model-onnx
time="2024-10-22T11:41:13.353Z" level=info msg="capturing logs" argo=true
time="2024-10-22T11:41:13.502Z" level=info msg="capturing logs" argo=true
I1022 11:41:13.584459      24 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "model_onnx__params": {
        "parameterType": "STRUCT",
        "defaultValue": {
          "path": ""
        },
        "isOptional": true
      }
    }
  },
  "outputDefinitions": {
    "artifacts": {
      "output": {
        "artifactType": {
          "schemaTitle": "system.Model",
          "schemaVersion": "0.0.1"
        }
      }
    },
    "parameters": {
      "Output": {
        "parameterType": "STRING"
      }
    }
  },
  "executorLabel": "exec-model-onnx"
}
I1022 11:41:13.588593      24 cache.go:116] Connecting to cache endpoint 10.43.199.76:8887
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[KFP Executor 2024-10-22 11:41:26,381 INFO]: --component_module_path is not specified. Looking for component `model_onnx` in config file `kfp_config.ini` instead
[KFP Executor 2024-10-22 11:41:26,384 INFO]: Loading KFP component "model_onnx" from catalogue/model_loaders/onnx.py (directory "catalogue/model_loaders" and module name "onnx")
[KFP Executor 2024-10-22 11:41:27,070 INFO]: Got executor_input:
{
    "inputs": {
        "parameterValues": {
            "model_onnx__params": {
                "path": "http://host.k3d.internal:5000/model.onnx"
            }
        }
    },
    "outputs": {
        "parameters": {
            "Output": {
                "outputFile": "/tmp/kfp/outputs/Output"
            }
        },
        "artifacts": {
            "output": {
                "artifacts": [
                    {
                        "type": {
                            "schemaTitle": "system.Model",
                            "schemaVersion": "0.0.1"
                        },
                        "uri": "minio://mlpipeline/v2/artifacts/tabular2/fa6ea65c-cf27-453e-87ed-bef66589b40c/model-onnx/output"
                    }
                ]
            }
        },
        "outputFile": "/tmp/kfp_outputs/output_metadata.json"
    }
}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 962, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 839, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 109, in <module>
    executor_main()
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main
    output_file = executor.execute()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor.py", line 361, in execute
    result = self.func(**func_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in kfp_method
  File "/usr/local/src/kfp/components/catalogue/model_loaders/onnx.py", line 14, in model_onnx
    with urllib.request.urlopen(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
I1022 11:41:27.718836      24 launcher_v2.go:151] publish success.
F1022 11:41:27.718924      24 main.go:49] failed to execute component: exit status 1
time="2024-10-22T11:41:28.529Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-10-22T11:41:29.382Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

**Comment by georgiosn** [comment]
Hello again I update the issue with the latest log I got while testing the new components.
This is the log from the component running in KFP.

time="2024-12-03T13:48:48.091Z" level=info msg="capturing logs" argo=true
time="2024-12-03T13:48:48.306Z" level=info msg="capturing logs" argo=true
I1203 13:48:48.885650      29 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "model_onnx__params": {
        "parameterType": "STRUCT",
        "defaultValue": {
          "path": ""
        },
        "isOptional": true
      }
    }
  },
  "outputDefinitions": {
    "artifacts": {
      "output": {
        "artifactType": {
          "schemaTitle": "system.Model",
          "schemaVersion": "0.0.1"
        }
      }
    }
  },
  "executorLabel": "exec-model-onnx"
}
I1203 13:48:48.914814      29 cache.go:116] Connecting to cache endpoint 10.43.199.76:8887
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[KFP Executor 2024-12-03 13:48:53,677 INFO]: --component_module_path is not specified. Looking for component `model_onnx` in config file `kfp_config.ini` instead
[KFP Executor 2024-12-03 13:48:53,679 INFO]: Loading KFP component "model_onnx" from catalogue/model_loaders/onnx.py (directory "catalogue/model_loaders" and module name "onnx")
[KFP Executor 2024-12-03 13:48:53,949 INFO]: Got executor_input:
{
    "inputs": {
        "parameterValues": {
            "model_onnx__params": {
                "path": "http://host.k3d.internal:5000/model.onnx"
            }
        }
    },
    "outputs": {
        "artifacts": {
            "output": {
                "artifacts": [
                    {
                        "type": {
                            "schemaTitle": "system.Model",
                            "schemaVersion": "0.0.1"
                        },
                        "uri": "minio://mlpipeline/v2/artifacts/run-components/4439bce0-31d5-44aa-a5a2-1db861b61c37/model-onnx/output"
                    }
                ]
            }
        },
        "outputFile": "/tmp/kfp_outputs/output_metadata.json"
    }
}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 962, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 839, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 109, in <module>
    executor_main()
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main
    output_file = executor.execute()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/executor.py", line 361, in execute
    result = self.func(**func_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in kfp_method
  File "/usr/local/src/kfp/components/catalogue/model_loaders/onnx.py", line 36, in model_onnx
    with urllib.request.urlopen(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
I1203 13:48:54.348192      29 launcher_v2.go:151] publish success.
F1203 13:48:54.348350      29 main.go:49] failed to execute component: exit status 1
time="2024-12-03T13:48:55.314Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-12-03T13:48:56.097Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1

**Comment by maniospas** [comment]
Closing this issue because it has been fixed. Discussion on integration issues continues in #44 .
